name: Genrate ASCII Artwork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: Install cowsay program
        run: sudo apt-get install cowsay -y
        
      - name: genrate ACII artwork
        run: cowsay -f dargon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Test file exists
        run: grep -i "dragon" dragon.txt 
      
      - name: read file
        run: cat dragon.txt
      - name: List Repo files
        run: ls -ltra